package uniDream;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import uniDream.entities.University;

@RestController // This means that this class is a Controller
@RequestMapping(path = "/v0") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UniversityRepository universityRepository;

//    @PostMapping(path = "/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser(@RequestParam String name
//            , @RequestParam String email) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setName(name);
//        n.setEmail(email);
//        userRepository.save(n);
//        return "Saved";
//    }

    @GetMapping(path = "/universities")
    public @ResponseBody Iterable<University> getAllUsers() {
        // This returns a JSON or XML with the users
        return universityRepository.findAll();
    }
}

